# NGINX - Easy

events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        server_name localhost;

        location / {
            root /tasks/nginx/easy;
            index index.html;
        }
    }
}
